CREATE TABLE `device_risk_assessments` (
  `id` VARCHAR(36) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `device_id` VARCHAR(100) NOT NULL,
  `score` INTEGER NOT NULL,
  `auto_banned` BOOLEAN NOT NULL DEFAULT false,
  `sim_present` BOOLEAN NOT NULL,
  `wechat_installed` BOOLEAN NOT NULL,
  `douyin_installed` BOOLEAN NOT NULL,
  `alipay_installed` BOOLEAN NOT NULL,
  `emulator_detected` BOOLEAN NOT NULL,
  `cloud_device_detected` BOOLEAN NOT NULL,
  `script_detected` BOOLEAN NOT NULL,
  `network_trusted` BOOLEAN NOT NULL,
  `ip_trusted` BOOLEAN NOT NULL,
  `location_distance_safe` BOOLEAN NOT NULL,
  `distance_meters` INTEGER NULL,
  `ip` VARCHAR(64) NULL,
  `detail` JSON NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `device_risk_assessments_user_id_created_at_idx` (`user_id`, `created_at`),
  INDEX `device_risk_assessments_score_created_at_idx` (`score`, `created_at`),
  CONSTRAINT `device_risk_assessments_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
